### PR TITLE
Add Slovenian translation

### PR DESCRIPTION
**Pull request by samolego**
Wasn't sure about boolean names, as `true=prav` by the translation, but `prav` is more used as `right` (~`wrong`), that's why I've gone with `da` (=`yes`)

also wasn't sure about the `GUI` word, slovenian counterpart is `GUV` which no one uses, though `GUI` is not really used well. I'd propose using the word `meni` (=`menu`), though this differs from original then.

### CODE REVIEW

**Comment by isXander** [comment]
There is already a translation for yes and no being used from minecraft translation files. So maybe use prav?

**Comment by samolego** [comment]
Talked to some other guys and found a better word for the context. Also switched `gui` -> `meni`, as it's much more understandable.

**Comment by isXander** [comment]
👍

**Comment by isXander** [comment]
May I suggest you join [my discord server](https://short.isxander.dev/discord) where you will receive a special translator role where you will get notified when there are translation changes.

**Pull request merged**
